# NewSystem.AI Railway Deployment Configuration
# Deploys both frontend and backend services

[build]
builder = "DOCKERFILE"

[deploy]
numReplicas = 1
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# Backend Service
[[services]]
name = "newsystem-api"
source = "backend"
dockerfile = "backend/Dockerfile"

[services.variables]
APP_ENV = "production"
DEBUG = "false"
# Other environment variables will be set in Railway dashboard

[[services.healthcheck]]
path = "/health"
port = 8000
initialDelaySeconds = 30
periodSeconds = 10

# Frontend Service  
[[services]]
name = "newsystem-frontend" 
source = "frontend"
dockerfile = "frontend/Dockerfile"

[[services.healthcheck]]
path = "/"
port = 3000
initialDelaySeconds = 15
periodSeconds = 10

# Database (using Railway PostgreSQL addon)
[[services]]
name = "newsystem-db"
plugin = "postgresql"

# Redis (for background jobs in production)
[[services]]
name = "newsystem-redis"
plugin = "redis"